### ISSUE TITLE
Code not working in mitsuba 0.6

### ISSUE THREAD

**Issue by bfraboni** [wangningbei/sourceCodeMBBRDF#1]
Hi Bei,

Thanks for providing the code alongside your article. I wanted to produce some comparison images and timings this last day, and couldn't get the scene  from Eric Heitz [mitsuba reference code](https://eheitzresearch.wordpress.com/240-2/) working with your model.

- The code from 2022 render the following with default params:
![scene_test_conductor](https://github.com/wangningbei/sourceCodeMBBRDF/assets/25059659/f9266209-ceab-4e4b-acd6-bd181e297d2f)
- The code from 2022 just crashes if I set `order = 10`
- The code from 2023 just segfaults and have a ton of divide by zero
- Note that I also compiled the code from Eric successfully, I can get the scene rendered:
![scene_test_conductor](https://github.com/wangningbei/sourceCodeMBBRDF/assets/25059659/7f1a872d-853e-4c62-92e2-cf208f7cfc52)

Is there any other modifications of the codebase I should be aware of to make the code working ?  

Thanks,

Basile

**Comment by ib00** [comment]
I noticed similar problem. 

@bfraboni Did you get this to work?

**Comment by bfraboni** [comment]
@ib00 unfortunately no, I gave up after few iterations on it.

**Comment by wangningbei** [comment]
Sorry for the late response. This crash is due to the random number issue and has been fixed. We did not meet this problem previously, when we use the path integrator. Please let us know if further issues have been found.

**Comment by bfraboni** [comment]
Thank you @wangningbei , Closing this one !
